zeebe:
  client:
    security:
      plaintext: true
    broker:
      gateway-address: localhost:26500
    request-timeout: PT60S


server.port: 8090
operate:
  client:
    base-url: http://localhost:8081
    authentication:
      simple:
        username: demo
        password: demo

camunda7:
  client:
    base-url: http://localhost:8080
    rest-api-context: engine-rest
    check-on-init: true
