camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
#  max-tasks: 1
#  lock-duration: 20000
  worker-id: spring-boot-worker-1
logging:
  level:
    "[org.apache.http]": INFO
    "[org.camunda.bpm.client.spring]": DEBUG